export enum InvoiceActionTypes {
  invoice_SET_INVOICE = 'invoice_SET_INVOICE',
  invoice_SET_TEMPO = 'invoice_SET_INVOICE_TEMPO',
  invoice_SET_DIALOG_CLIENTE = 'invoice_SET_DIALOG_CLIENTE',
  invoice_SET_DIALOG_EQUIPAMENTO = 'invoice_SET_DIALOG_EQUIPAMENTO',
  invoice_SET_DIALOG_SOLICITACAO_ASSISTENCIA = 'invoice_SET_DIALOG_SOLICITACAO_ASSISTENCIA',
  invoice_SET_DIALOG_SERVICOS_EFETUADOS = 'invoice_SET_DIALOG_SERVICOS_EFETUADOS',
  invoice_SET_DIALOG_MATERIAIS = 'invoice_SET_DIALOG_MATERIAIS',
  invoice_SET_DIALOG_VALIDACOES = 'invoice_SET_DIALOG_VALIDACOES',

}
