name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Update Browserslist DB
        run: npx update-browserslist-db@latest

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Token for deployment
